//#define PICO_DEFAULT_UART 0
//#define PICO_DEFAULT_UART_TX_PIN 0
//#define PICO_DEFAULT_UART_RX_PIN 1

//#define PICO_DEFAULT_UART 1
//#define PICO_DEFAULT_UART_TX_PIN 4
//#define PICO_DEFAULT_UART_RX_PIN 5

//#define PICO_DEFAULT_UART 1
//#define PICO_DEFAULT_UART_TX_PIN 8
//#define PICO_DEFAULT_UART_RX_PIN 9

// Works!
#define PICO_DEFAULT_UART 0
#define PICO_DEFAULT_UART_TX_PIN 12
#define PICO_DEFAULT_UART_RX_PIN 13

// Works!
//#define PICO_DEFAULT_UART 0
//#define PICO_DEFAULT_UART_TX_PIN 16
//#define PICO_DEFAULT_UART_RX_PIN 17




